version: '3'

services:
  model:
    container_name: model
    restart: always
    build: apps
    expose:
      - "8111"
#    command: gunicorn -w 1 -b 127.0.0.1:8111 wsgi:app_server
    command: python wsgi.py
    volumes:
      - ./outputs:/outputs
      - ./logs:/usr/src/app/logs
#    deploy:
#      resources:
#        limits:
#          cpus: '0.50'
#        reservations:
#          devices:
#            - driver: nvidia
#              count: "all"
#              capabilities: [gpu]
  nginx:
    container_name: nginx
    restart: always
    build: nginx
    ports:
      - "8099:80"
    depends_on:
      - model
    volumes:
      - ./outputs:/outputs
