version: '3'

services:
  model:
    container_name: model
    restart: always
    build: apps
    image: encrypt_model
    expose:
      - "8111"
    environment:
      - HOST_IP=127.0.0.1
      - LOG_LEVEL=10
    command: gunicorn -w 1 -b 0.0.0.0:8111 wsgi:app_server
    volumes:
      - ./outputs:/outputs
      - ./logs:/var/log/apps
  nginx:
    container_name: nginx
    restart: always
    build: nginx
    image: encrypt_nginx
    ports:
      - "8099:80"
    depends_on:
      - model
    volumes:
      - ./outputs:/outputs
